data:extend({
  {
    type = "double-setting",
    name = "flo-radius-mult",
    setting_type = "runtime-global",
    default_value = 0.1,
    minimum_value = 0,
    maximum_value = 1000,
    order = "a[explosion]-a[radius-multiplier]",
  },
  {
    type = "double-setting",
    name = "flo-damage-mult",
    setting_type = "runtime-global",
    default_value = 5,
    minimum_value = 0,
    maximum_value = 1000,
    order = "a[explosion]-b[damage-multiplier]",
  },
  {
    type = "double-setting",
    name = "flo-radius-power",
    setting_type = "runtime-global",
    default_value = 2.5,
    minimum_value = 1,
    maximum_value = 10,
    order = "a[explosion]-c[radius-scaling]",
  },
  {
    type = "double-setting",
    name = "flo-damage-power",
    setting_type = "runtime-global",
    default_value = 2.5,
    minimum_value = 1,
    maximum_value = 10,
    order = "a[explosion]-d[damage-scaling]",
  },
  {
    type = "double-setting",
    name = "flo-min-energy-mj",
    setting_type = "runtime-global",
    default_value = 10,
    minimum_value = 0,
    maximum_value = 1000000000,
    order = "a[explosion]-e[minimum-energy]",
  },
  {
    type = "double-setting",
    name = "flo-default-energy-mj",
    setting_type = "runtime-global",
    default_value = 0.45,
    minimum_value = 0,
    maximum_value = 1000,
    order = "a[explosion]-f[default-energy]",
  },
  {
    type = "double-setting",
    name = "flo-pollution-mult",
    setting_type = "runtime-global",
    default_value = 1,
    minimum_value = 0,
    maximum_value = 1000,
    order = "a[explosion]-g[pollution]",
  },
  {
    type = "double-setting",
    name = "flo-fire-spread-mult",
    setting_type = "runtime-global",
    default_value = 1,
    minimum_value = 0,
    maximum_value = 10,
    order = "a[explosion]-h[fire-spread]",
  },
  {
    type = "double-setting",
    name = "flo-ignition-delay-seconds",
    setting_type = "runtime-global",
    default_value = 0,
    minimum_value = 0,
    maximum_value = 60,
    order = "a[explosion]-i[ignition-delay]",
  },
  {
    type = "int-setting",
    name = "flo-max-explosions-per-tick",
    setting_type = "runtime-global",
    default_value = 100,
    minimum_value = 1,
    maximum_value = 10000,
    order = "a[explosion]-j[per-tick-limit]",
  },
  {
    type = "double-setting",
    name = "flo-chance-fire",
    setting_type = "runtime-global",
    default_value = 95,
    minimum_value = 0,
    maximum_value = 100,
    order = "b[ignition-chance]-a[fire]",
  },
  {
    type = "double-setting",
    name = "flo-chance-explosion",
    setting_type = "runtime-global",
    default_value = 75,
    minimum_value = 0,
    maximum_value = 100,
    order = "b[ignition-chance]-b[explosion]",
  },
  {
    type = "double-setting",
    name = "flo-chance-acid",
    setting_type = "runtime-global",
    default_value = 50,
    minimum_value = 0,
    maximum_value = 100,
    order = "b[ignition-chance]-c[acid]",
  },
  {
    type = "double-setting",
    name = "flo-chance-electric",
    setting_type = "runtime-global",
    default_value = 50,
    minimum_value = 0,
    maximum_value = 100,
    order = "b[ignition-chance]-d[electric]",
  },
  {
    type = "double-setting",
    name = "flo-chance-laser",
    setting_type = "runtime-global",
    default_value = 50,
    minimum_value = 0,
    maximum_value = 100,
    order = "b[ignition-chance]-e[laser]",
  },
  {
    type = "double-setting",
    name = "flo-chance-physical",
    setting_type = "runtime-global",
    default_value = 0,
    minimum_value = 0,
    maximum_value = 100,
    order = "b[ignition-chance]-f[physical]",
  },
  {
    type = "double-setting",
    name = "flo-chance-impact",
    setting_type = "runtime-global",
    default_value = 0,
    minimum_value = 0,
    maximum_value = 100,
    order = "b[ignition-chance]-g[impact]",
  },
  {
    type = "double-setting",
    name = "flo-chance-poison",
    setting_type = "runtime-global",
    default_value = 0,
    minimum_value = 0,
    maximum_value = 100,
    order = "b[ignition-chance]-h[poison]",
  },
  {
    type = "double-setting",
    name = "flo-chance-other",
    setting_type = "runtime-global",
    default_value = 0,
    minimum_value = 0,
    maximum_value = 100,
    order = "b[ignition-chance]-i[other]",
  },
  {
    type = "string-setting",
    name = "flo-fluid-whitelist",
    setting_type = "runtime-global",
    default_value = "",
    allow_blank = true,
    order = "c[fluid-filters]-a[whitelist]",
  },
  {
    type = "string-setting",
    name = "flo-fluid-blacklist",
    setting_type = "runtime-global",
    default_value = "",
    allow_blank = true,
    order = "c[fluid-filters]-b[blacklist]",
  },
  {
    type = "bool-setting",
    name = "flo-enable-pipes",
    setting_type = "runtime-global",
    default_value = true,
    order = "d[entity-filters]-a[pipes]",
  },
  {
    type = "bool-setting",
    name = "flo-enable-storage-tanks",
    setting_type = "runtime-global",
    default_value = true,
    order = "d[entity-filters]-b[storage-tanks]",
  },
  {
    type = "bool-setting",
    name = "flo-enable-fluid-wagons",
    setting_type = "runtime-global",
    default_value = true,
    order = "d[entity-filters]-c[fluid-wagons]",
  },
  {
    type = "bool-setting",
    name = "flo-enable-production-machines",
    setting_type = "runtime-global",
    default_value = true,
    order = "d[entity-filters]-d[production-machines]",
  },
  {
    type = "bool-setting",
    name = "flo-enable-pumps",
    setting_type = "runtime-global",
    default_value = false,
    order = "d[entity-filters]-e[pumps]",
  },
  {
    type = "bool-setting",
    name = "flo-enable-other-entities",
    setting_type = "runtime-global",
    default_value = true,
    order = "d[entity-filters]-f[other]",
  },
  {
    type = "bool-setting",
    name = "flo-enable-solid-items",
    setting_type = "runtime-global",
    default_value = false,
    order = "e[solid-items]-a[master]",
  },
  {
    type = "bool-setting",
    name = "flo-solid-items-on-belts",
    setting_type = "runtime-global",
    default_value = true,
    order = "e[solid-items]-b[locations]-a[belts]",
  },
  {
    type = "bool-setting",
    name = "flo-solid-items-on-ground",
    setting_type = "runtime-global",
    default_value = true,
    order = "e[solid-items]-b[locations]-b[ground]",
  },
  {
    type = "bool-setting",
    name = "flo-solid-items-in-containers",
    setting_type = "runtime-global",
    default_value = true,
    order = "e[solid-items]-b[locations]-c[containers]",
  },
  {
    type = "bool-setting",
    name = "flo-enable-wood-fires",
    setting_type = "runtime-global",
    default_value = true,
    order = "e[solid-items]-c[item-types]-a[wood]",
  },
  {
    type = "bool-setting",
    name = "flo-enable-coal-fires",
    setting_type = "runtime-global",
    default_value = true,
    order = "e[solid-items]-c[item-types]-b[coal]",
  },
  {
    type = "bool-setting",
    name = "flo-enable-solid-fuel-fires",
    setting_type = "runtime-global",
    default_value = true,
    order = "e[solid-items]-c[item-types]-c[solid-fuel]",
  },
  {
    type = "bool-setting",
    name = "flo-enable-rocket-fuel-fires",
    setting_type = "runtime-global",
    default_value = true,
    order = "e[solid-items]-c[item-types]-d[rocket-fuel]",
  },
  {
    type = "bool-setting",
    name = "flo-enable-filled-barrel-fires",
    setting_type = "runtime-global",
    default_value = true,
    order = "e[solid-items]-c[item-types]-e[filled-barrels]",
  },
  {
    type = "bool-setting",
    name = "flo-enable-flamethrower-ammo-fires",
    setting_type = "runtime-global",
    default_value = true,
    order = "e[solid-items]-c[item-types]-f[flamethrower-ammo]",
  },
  {
    type = "int-setting",
    name = "flo-max-solid-updates-per-tick",
    setting_type = "runtime-global",
    default_value = 100,
    minimum_value = 1,
    maximum_value = 10000,
    order = "e[solid-items]-d[performance]",
  },
})
